name: API Request Trigger

on:
  workflow_dispatch:  # Allows manual trigger via API request

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Get Song Info
        env:
          API_KEY: ${{ secrets.MM_API_KEY }}  # Access the stored API key
        run: |
          curl --request GET \
                --url https://api.musixmatch.com/ws/1.1/track.search
