name: Manual Trigger

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use GitHub Secret
        env:
          GITHUB_PAT: ${{ secrets.PAT }}  # Use the secret stored in GitHub
        run: |
          echo "Workflow triggered using a secure PAT!"
          echo "PAT is available but not exposed in logs."
