name: API Request Trigger

on:
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger API Using GitHub Secrets
        env:
          API_KEY: ${{ secrets.MM_API_KEY }}  # Your API key
          GITHUB_PAT: ${{ secrets.PAT }}  # Your GitHub PAT
        run: |
          curl --request GET \
                -H "Authorization: Bearer $API_KEY" \
                --url https://api.musixmatch.com/ws/1.1/track.search
